[package]
name = "io-lifetimes"
version = "0.1.1-alpha.0"
description = "A low-level I/O ownership and borrowing library"
authors = ["Dan Gohman <dev@sunfishcode.online>"]
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["api", "io"]
categories = ["os", "rust-patterns"]
edition = "2018"
repository = "https://github.com/sunfishcode/io-lifetimes"
exclude = ["/.github"]

[build-dependencies]
rustc_version = "0.4.0"

[dependencies]

[target.'cfg(not(windows))'.dependencies]
libc = "0.2.96"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["handleapi", "std", "winsock2"] }

[badges]
maintenance = { status = "actively-developed" }
